<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledger.Domain\Ledger.Domain.csproj" />
    <ProjectReference Include="..\Ledger.Ingestion\Ledger.Ingestion.csproj" />
    <ProjectReference Include="..\Ledger.Persistence\Ledger.Persistence.csproj" />
  </ItemGroup>

</Project>
